### ISSUE TITLE
Errors on the geometry_calculations class

### ISSUE THREAD

**Issue by petsinis** [renatofreitas91/atc_code#1]
First of all, at the specific class every time user puts a negative number as a value of a side (on each of the 13 shapes) it is acceptable by the programm, something that is mathimatically wrong.

Secondly, the value "i" it is also acceptable from the system and it has the same value as "zero" 0.

In every triangle with sides a,b,c it is known that (a+b>c AND a+c>b AND b+c>a) for example if a=3 ,b=4, c=5 then 3+4>5 AND 3+5>4 AND 4+5>3 so this values can be sides of a tringle and must be acceptable. Although, the programm accepts values that can not be sides of a triangle, for example if the user gives  base=a=10 ,side1=b=3,side2=c=4 then we have 10+3>4 AND 10+4>3 but not  3+4>10 .
A similar problem user meets at Trapezoid and Parallelogram calculations.

Also, when user choose the option 12 the programm must return the Volume and the Surface Area of the given Square or Rectangular Pyramid ,but only the Volume appears on the screen and not the Surface Area.

Last of all, when the calculating finishes the programm asks the user if he wants to continue "Continue? (Yes -> 1 / No -> 0)" but the system takes the other numbers as Yes ,something that is not well known to the user.

**Comment by renatofreitas91** [comment]
Fixed in ATC v2.0.1
